"""create settlements table

Revision ID: 14d4e95dc4dc
Revises: 629d9e7ac0a2
Create Date: 2026-09-01 16:28:30.079197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d4e95dc4dc'
down_revision: Union[str, Sequence[str], None] = '629d9e7ac0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('settlement_id', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    # ### end Alembic commands ###
