"""add audit logs

Revision ID: 832533f1f844
Revises: bcf9531b54e8
Create Date: 2026-09-03 11:20:40.281407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832533f1f844'
down_revision: Union[str, Sequence[str], None] = 'bcf9531b54e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('controlled_action_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('CONTROLLED_ACTION_CREATED', 'CONTROLLED_ACTION_STARTED', 'CONTROLLED_ACTION_COMPLETED', 'CONTROLLED_ACTION_FAILED', 'CONTROLLED_ACTION_REJECTED', name='auditeventtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_controlled_action_id'), 'audit_logs', ['controlled_action_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_payment_id'), 'audit_logs', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_payment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_controlled_action_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
