"""add controlled actions

Revision ID: 9e28d8768411
Revises: d12f6209e0b3
Create Date: 2026-09-03 10:56:26.125577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e28d8768411'
down_revision: Union[str, Sequence[str], None] = 'd12f6209e0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controlled_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('INVESTIGATE_MISSING_SETTLEMENT', 'REVIEW_SETTLEMENT_AMOUNT', 'REVIEW_CURRENCY_MISMATCH', 'INVESTIGATE_INVALID_STATE', name='controlledactiontype'), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'REJECTED', name='controlledactionstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['transactions.payment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controlled_actions_id'), 'controlled_actions', ['id'], unique=False)
    op.create_index(op.f('ix_controlled_actions_payment_id'), 'controlled_actions', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controlled_actions_payment_id'), table_name='controlled_actions')
    op.drop_index(op.f('ix_controlled_actions_id'), table_name='controlled_actions')
    op.drop_table('controlled_actions')
    # ### end Alembic commands ###
