"""add payment event timestamp

Revision ID: a68748a44dd7
Revises: 14d4e95dc4dc
Create Date: 2026-09-01 17:03:10.125007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68748a44dd7'
down_revision: Union[str, Sequence[str], None] = '14d4e95dc4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'paid_at')
    # ### end Alembic commands ###
