"""add exception lifecycle

Revision ID: d12f6209e0b3
Revises: a68748a44dd7
Create Date: 2026-09-02 17:23:51.602404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12f6209e0b3'
down_revision: Union[str, Sequence[str], None] = 'a68748a44dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exception_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='exceptionlifecyclestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exception_records_id'), 'exception_records', ['id'], unique=False)
    op.create_index(op.f('ix_exception_records_payment_id'), 'exception_records', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exception_records_payment_id'), table_name='exception_records')
    op.drop_index(op.f('ix_exception_records_id'), table_name='exception_records')
    op.drop_table('exception_records')
    # ### end Alembic commands ###
